name: I Love Estonia
favicon: null
layout_spectrum: 0.5680851
typography_spectrum: 1
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fae9c8'
    - '#0e327b'
    - '#197fa6'
    - '#25cfb3'
    - '#fa759f'
  brandStrength: 0.875
  lightness: 0.375
  saturation: 0.5625
  rhythmicContrast: 1
purpose: []
