name: I Love Estonia
favicon: null
layout_spectrum: 0.49282
typography_spectrum: 0.9399
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f1223'
    - '#2a5679'
    - '#e5ba87'
    - '#d43e59'
    - '#bd0b29'
  brandStrength: 1
  lightness: 0.875
  saturation: 0.375
  rhythmicContrast: 1
purpose: []
