favicon: null
name: I Love Estonia
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.5625
  brandStrength: 0.7680851
  lightness: 0.06595745
  brandColors:
    - '#FFFFFF'
    - '#1A1F25'
    - '#B2A175'
    - '#876E46'
    - '#A6BAC1'
  rhythmicContrast: 1
typography_spectrum: 0.8382978
layout_spectrum: 0.1893617
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
