name: I Love Estonia
favicon: null
layout_spectrum: 0.62037
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffd'
    - '#3664a6'
    - '#00b6c8'
    - '#5ce0e0'
    - '#8e98ba'
  brandStrength: 1
  lightness: 0.125
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
