name: I Love Estonia
favicon: null
layout_spectrum: 0.62538
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7d1bb'
    - '#191722'
    - '#58443d'
    - '#f9faf5'
    - '#b9a98f'
  brandStrength: 0.5625
  lightness: 0.125
  saturation: 0.6875
  rhythmicContrast: 1
purpose: []
