name: I Love Estonia
favicon: null
layout_spectrum: 0.27952
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cfe8e5'
    - '#bb1e27'
    - '#e3a22e'
    - '#557531'
    - '#92b15d'
  brandStrength: 0.3125
  lightness: 0.875
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
